timeout: 7200s # 2 hours
substitutions:
  _GRAALVM_VERSION: '22.3.1'
steps:
  - name: gcr.io/cloud-builders/docker
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/graalvm:${_GRAALVM_VERSION}", "--build-arg=GRAALVM_VERSION=$_GRAALVM_VERSION", "." ]
    dir: java/graalvm
    id: graalvm-build
    waitFor: [ "-" ]
